### ISSUE TITLE
Page "Reports" does not respond and does not translate

### ISSUE THREAD

**Issue by amandajurno** [WikiMovimentoBrasil/capx-frontend#29]
**Describe the feature or bug**
In addition to not being translated into Portuguese, the "Reports" tab does not respond to clicks and does not open the appropriate page.

**If it is a bug, describe the steps to reproduce the behavior:**
1. Go to 'https://capx.toolforge.org/reports'
2. Select 'any language'
3.  See error

**Expected behavior**
Reports page must respond to click and load with properly language selected.

**Screenshots**
![image](https://github.com/user-attachments/assets/54cb88fc-bb23-4adb-b0b0-0d14c46a0ba6)

**Additional context**

**Comment by victorgois** [comment]
Reports page working and translations are functional

https://github.com/user-attachments/assets/976c7511-a72a-4242-9f04-c6807ddcc2f9
